### PR TITLE
Fix/no network infinite loading

### LINKED ISSUE #558: No wallets can be paired if there is no network, or a server is down
**Describe the bug (current behavior)**
If there is no network, or potentially if some servers cannot be reached (eg. matrix or wc2), then the whole UI is stuck and no wallet can be paired, not even browser extensions.

**To Reproduce**
1. open dapp
2. go offline (eg. network settings in chrome)
3. open pairing modal
4. click temple
The UI is now stuck on the loader.

**Expected (correct) behavior**
To be defined. The loader is shown because the network request failed. The network request must succeed to pair with P2P / WC2 wallets. But it is not required for pairing with extension wallets. The problem is that with the new UI, both options are shown side by side, so we currently are waiting for the network response. Maybe the solution would be to not make the loader "global" but rather only show where the P2P/WC2 options will be displayed, but already show the "connect to extension" button.

### PR DESCRIPTION
**Pull request by IsaccoSordo**
This PR should fix #558

### CODE REVIEW

File: packages/beacon-ui/src/ui/alert/index.tsx [hunk 1]
```diff
@@ -171,8 +163,12 @@ const openAlert = async (config: AlertConfig): Promise<string> => {
     const setDefaultPayload = async () => {
       if (config.pairingPayload) {
         const serializer = new Serializer()
-        const codeQR = await serializer.serialize(await p2pPayload)
-        setCodeQR(codeQR)
+        try {
+          const codeQR = await serializer.serialize(await p2pPayload)
+          setCodeQR(codeQR) 
+        } catch(error: any) {
+          console.error("Cannot connect to netwrok: ", error.message)
```
Comment (jsamol) [inline packages/beacon-ui/src/ui/alert/index.tsx:170]: Tiny typo here 😅

**Review by jsamol — APPROVED** [review]
