### PR TITLE
Fix/ack flow

### LINKED ISSUE #617: ACK on permission requests not working
**Describe the bug (current behavior)**
No ACK on permission request. As a consequence of that, Beacon will tell the user that the wallet is unresponsive when it's not.

**To Reproduce**
1. Send a permission request

**Expected (correct) behavior**
ACK should be sent on all kind of requests. Even permission requests.

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

### PR DESCRIPTION
**Pull request by IsaccoSordo**
This PR should fix #617, #623
-  removed tezos_getAcknowledgement (a session without session_properties is still necessary to trigger the new flow)
- also resolved multiple instances of "stuck state"

### CODE REVIEW

File: packages/beacon-dapp/src/dapp-client/DAppClient.ts [hunk 1]
```diff
@@ -435,9 +435,11 @@ export class DAppClient extends Client {
       }
     })()
 
-    await (isWaiting
-      ? this.events.emit(BeaconEvent.WC_ACKNOWLEDGE_PENDING, { walletInfo })
-      : this.events.emit(BeaconEvent.WC_ACKNOWLEDGE_RECEIVED, { walletInfo }))
+    console.log('walletInfo: ', walletInfo)
+
+    setTimeout(async () => await this.events.emit(BeaconEvent.HIDE_UI, ['alert']))
```
Comment (AndreasGassmann) [inline packages/beacon-dapp/src/dapp-client/DAppClient.ts:440]: I think we don't need to "async/await" here.

Why do we need to hide the UI? Does updating the toast not automatically dismiss the old toast?

File: packages/beacon-dapp/src/dapp-client/DAppClient.ts [hunk 2]
```diff
@@ -1499,7 +1505,7 @@ export class DAppClient extends Client {
 
     if (!walletInfo) {
       walletInfo = {
-        name: selectedPeer?.name ?? '',
+        name: selectedPeer?.name ?? (await this.getWalletInfoFromStorage()) ?? '',
```
Comment (AndreasGassmann) [inline packages/beacon-dapp/src/dapp-client/DAppClient.ts:1508]: Why is the "selectedPeer" not defined after a refresh?

File: packages/beacon-dapp/src/dapp-client/DAppClient.ts [hunk 3]
```diff
@@ -1549,8 +1560,8 @@ export class DAppClient extends Client {
       }
 
       return {
-        name: walletInfo.name,
-        icon: walletInfo.icon ?? selectedApp.logo,
+        name: selectedApp ? selectedApp.name : walletInfo.name,
```
Comment (AndreasGassmann) [inline packages/beacon-dapp/src/dapp-client/DAppClient.ts:1563]: This means that we will use the "last selected" app over the name that we have stored in the wallet info. Is that what we want? We could do `name: walletInfo.name ?? selectedApp?.name`.

File: packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts [hunk 4]
```diff
@@ -422,10 +395,16 @@ export class WalletConnectCommunicationClient extends CommunicationClient {
...
-        const session = await this.openSession(topic)
+        let session = await this.openSession(topic)
+
+        if (!session.sessionProperties) {
+          const fun = this.eventHandlers.get(ClientEvents.WC_ACK_NOTIFICATION)
+          fun && fun()
+          this.requestAccountNamespacePromise = new ExposedPromise()
+          await this.requestAccountNamespacePromise?.promise
+          session = this.getSession()
+        }
```
Comment (AndreasGassmann) [inline packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts:406]: This code looks very similar to the one in the `requestPermissions` method. Shouldn't only one of those 2 be needed?

**Review by AndreasGassmann — CHANGES_REQUESTED** [review]
